// Bump this like a real product would: patch for a small fix, minor for a
// Core Update or DLC pack landing, major for something that changes the
// game in a fundamental way. Add a matching CHANGELOG entry (newest first)
// whenever the version bumps - that's what WhatsNewModal reads from.
export const APP_VERSION = "2.7.0";

export type ChangelogEntry = {
  version: string;
  title: string;
  highlights: string[];
};

export const CHANGELOG: ChangelogEntry[] = [
  {
    version: "2.7.0",
    title: "Body, Mind & Things To Do",
    highlights: [
      "Body & Fitness: choose what you eat (junk to strict plan) and how you move (nothing to intense training). Your hidden weight, fitness, energy and looks follow, and so does your risk of illness. Overdo it and you'll get injured. Book yearly check-ups that catch problems early",
      "Habits & dependence: alcohol, nicotine, gambling, drugs and screens can take hold. Once you're hooked it plays out every year: cost, health, mood, work performance, and the people who love you. Get out with cold turkey, a support group or rehab, and watch out for relapses",
      "Your habits now show up in your health: smoking, drinking, drugs and weight raise the odds of heart disease, cancer, diabetes and a new liver disease",
      "Hobbies: 25 hobbies from running and football to painting, guitar, chess and coding. They level up with practice, hit milestones, and turn into races, gigs, exhibitions, book deals and sales. Up to three at once",
      "Mind & Habits: meditation, volunteering, and a faith or spirituality of your choice with a community to go with it",
      "Achievements and a bucket list: 61 things a life can add up to, pinned goals with progress bars, a life score, and a proper summary when it ends",
      "Family tree: parents, partner, siblings, children and grandchildren in one place",
      "Plan your wedding: pick the kind of day (registry to lavish), who's invited, deal with what goes wrong, and choose a honeymoon. What it costs depends on where you live",
      "Six new things to do with people: ask their advice, do or ask a favour, share a hobby, check in on someone who's unwell, and couples counselling",
      "About 175 new events (the pool now tops 440): in-laws, reunions, caring for parents, block parties, jury duty, drug offers, family interventions, midlife crises, first concerts, driving lessons, retirement memoirs and a great many small joys and disasters",
    ],
  },
  {
    version: "2.6.0",
    title: "Working Life & Money",
    highlights: [
      "Real careers: every full-time job now sits on a ladder from entry level to executive, with proper titles (Junior to Senior to Lead to Manager to Director to Chief) and pay that climbs with each rung",
      "Annual performance reviews: your smarts, aptitude, personality, experience, health, stress and how hard you work all feed a performance score. See exactly what's helping or hurting it, then choose whether to coast, work steadily or grind",
      "Raises, bonuses and promotions you earn, plus the option to ask for a raise or a promotion once a year (and pay for a refusal with your boss's goodwill)",
      "Trouble at work is real: performance improvement plans, dismissals, redundancies in recessions, and severance pay. Unions protect you from layoffs at the cost of dues",
      "Unemployment benefits, severance and state pensions now differ by country: 12 tax systems with their own brackets, social contributions and child credits. A new Taxes screen shows what you pay and what you get back",
      "Build a network, take training courses, get headhunted, mentored, burned out or called out for whistleblowing: 31 new workplace, business and money events",
      "Start your own business: ten types from a food truck to a tech start-up, with staff, marketing, expansion, reputation, bad years, bankruptcy and buy-out offers. Run it alongside a job or go all in",
      "Retire when you like from 55; the state pension starts at your country's retirement age",
      "More ways to grow money: idle cash earns interest, plus a global index fund, a treasury bond and a wildly volatile coin. Buy rental property and collect rent (or chase a late tenant)",
      "Bankruptcy is a real, painful last resort that wipes your debts and wrecks your credit for seven years",
      "Interviews ask field-specific questions: technical ones for tech jobs, patient scenarios for healthcare, safety questions for trades, and more",
      "Prices now creep up about 2% a year and pay is sized to match, so long lives don't end in runaway wealth. Fixed a bug where the pay you were offered was scaled by your country and city twice, which made non-US wages far too low",
    ],
  },
  {
    version: "2.5.0",
    title: "Across Borders",
    highlights: [
      "You can leave the country. Across Borders (under Activities) is a new hub: move abroad, your passport and languages, travel, and citizenship",
      "Six visa routes - study, skilled worker, investor, working holiday, marriage, and permanent residence - each with real requirements shown as a checklist, a fee, a waiting time and your odds. Applications are decided at the next birthday and can be refused",
      "Every country has its own attitude: how welcoming it is, its language, how long until citizenship, whether it allows dual citizenship, and how strong its passport is",
      "Actually moving abroad is a big deal: you leave your job and sell your home, friends and family drift, you're homesick, your credit history stays behind, and you start in a rented room in a new city. Sponsored workers arrive with a job",
      "Languages are real (English, Spanish, Portuguese, French, German, Japanese, Korean, Hindi). You pick up the local one by living there, can take lessons, and it gates visas and citizenship",
      "Feeling settled is tracked as you integrate: culture shock, discrimination, kind locals, expat communities, homesick holidays",
      "Visas expire: renew with a job or studies, get sponsored by an employer, hire a lawyer - or overstay and be deported",
      "Become a citizen: years of residence, the language, a clean record and a citizenship test. Some countries make you give up your old passport",
      "Travel: take one trip a year to any country. Strong passports get in visa-free; weaker ones need a tourist visa that can be refused. Collect passport stamps",
      "New events: a recruiter overseas offers a sponsored job, your parents ask for money from home, the family emigrates when you're a kid, and older emigrants ask whether it's time to go home",
    ],
  },
  {
    version: "2.4.0",
    title: "The World",
    highlights: [
      "Twelve countries to be born in: the United States, United Kingdom, Nigeria, Japan, Brazil - plus Canada, Australia, Germany, France, India, Mexico and South Korea, each with its own names, exams, universities, tax, healthcare and wages",
      "Sixty-one cities. Pick where you're born or leave it to fate. Every city has a size (capital, big city, mid-size, small town), a cost of living, a wage level, a safety rating, school quality and the job fields it's strong in",
      "Where you live matters: pay follows your city's wage index, schools follow its quality, job listings favour its strong industries, and safe or rough streets change what happens to you",
      "Home & Moving is a proper hub: see your city, move to another one, rent a place, buy or sell a home, and manage your budget",
      "Renting is real: a room in a shared house up to a whole rented house, with a deposit, rent that creeps up every year, rent-hike and landlord events, and eviction if you fall behind - back to family or, worst case, the street",
      "Moving is a decision with consequences: a preview of the pay and rent change, whether your job comes with you, homesickness, friends who drift, a partner who may not follow, new neighbours and (for kids) a new school",
      "Families relocate too - some childhoods now involve a move to another city",
      "Everyday costs are finally charged: food, bills and getting around, scaled by country and city, with three lifestyles (frugal, comfortable, living well) that change your mood and your bank balance",
      "A Budget screen shows last year's take-home, rent, living costs and what was left over",
      "Home prices scale with the city and country, and the housing market moves - your home can gain or lose value, and you pay property tax and upkeep",
      "18 new place-driven events: noisy neighbours, a friendly neighbour, unpaid-rent notices, burglaries, the festival that takes over your city, the small-town rumour mill, big-city loneliness, a sudden offer on your house",
    ],
  },
  {
    version: "2.3.0",
    title: "Beyond High School",
    highlights: [
      "Getting into university is a real process: sit your country's entrance exam (SAT, A-levels, JAMB, Japan's Common Test, ENEM), take a prep course, and ask teachers for recommendation letters",
      "38 institutions across the five countries - community colleges, state and private universities, elite schools, online universities and trade schools - each with its own admissions bar, cost, prestige and campus",
      "Apply to up to five with a major from 32 (each with its own difficulty, pay and job field). Every school shows Safety / Match / Reach odds for you, and results come with scholarships, need-based grants and what your family will chip in",
      "Pay for it yourself: your cash first, then a student loan that builds interest while you study and starts repayment when you leave",
      "Real university years: grades depend on the major, the school's prestige and how you study; make the dean's list; get put on probation - and dismissed. Change major, transfer schools, choose where to live, or drop out",
      "Associate degrees carry two years of credit into a university. Graduating gives a degree with honours (cum laude, First-class...) and a graduation to mark",
      "Trades and apprenticeships: certificates in electrical, plumbing, carpentry, welding, culinary and more - and paid apprenticeships that pay you to learn",
      "Grad school: master's, MBA, law, medicine, pharmacy, teaching and PhD, with real entry requirements",
      "What you studied matters at work: Doctor, Lawyer, Pharmacist, Nurse and Teacher now need the right degree; a matching degree, a prestigious school, a good GPA and internships help at interviews and lift your starting salary",
      "New campus events: career fairs, research offers, roommate wars, tuition hikes, scholarship reviews, thesis crunch, return offers",
    ],
  },
  {
    version: "2.2.0",
    title: "Growing Up",
    highlights: [
      "School is a real system now: you go to an actual school (public, private, magnet or boarding), and its quality helps decide your grades",
      "Every year ends with a report card - subject grades, GPA, your class rank, the honour roll and a teacher's comment - shown in your country's style (letters, GCSE grades, WAEC, 5-point, out of 10)",
      "Choose how hard you work (study hard, steady, or take it easy), stay after class for a teacher's help, and see the guidance counsellor to set a plan",
      "Behaviour matters: detention, suspensions and expulsion (to an alternative school). Fail a year and you're offered summer school. Drop out - only once you're old enough where you live - and take the GED later",
      "Popularity and cliques (Jocks, Nerds, Artsy, Popular, Loners) with real effects, and bullying from both sides: get bullied and choose how to respond, or decide what kind of person you'll be when the crowd starts laughing",
      "17 clubs and teams with tryouts, skills that grow, captains and injuries - up to three at a time",
      "Childhood finally has a childhood: 30+ new events from teething and first words to birthday parties, summer camps, screen-time fights, lemonade stands, road trips and the winter present you ask for - and how your parents raised you nudges your personality",
      "Kids can do chores for pocket money from 6, and stress, happiness and smarts no longer sit near their maximum through childhood",
    ],
  },
  {
    version: "2.1.0",
    title: "Getting Hired",
    highlights: [
      "Work is now three separate things: part-time jobs, full-time careers, and gigs (babysitting, tutoring, lawn mowing and handyman jobs, dog walking, busking, freelancing, delivery, rideshare and more)",
      "Legal working ages depend on where you were born - odd jobs from 12-14, part-time from 15-16, full-time from 18. Under 16 you need a parent's permission",
      "Tap any job to open a real listing: the company (generated for every opening) with its size, culture, perks, commute and employee rating, the pay, the hours, a typical day, where it leads - and every requirement checked live",
      "Press Apply and you sit an actual interview: 3-5 questions from a bank of 100+, some genuine, some situational, some curveballs (how many golf balls fit in a school bus?) and some pure nonsense (what's your spirit sandwich?)",
      "How you answer matters - your personality, smarts, looks, experience and skills shape the result, jokes only land if the interviewer has a sense of humour, and lying can get you caught",
      "Offers you can accept, negotiate or turn down; a \"we'll be in touch\" that gets answered next year; and rejections with feedback (and a cooldown before you can apply to the same place again)",
      "Gigs build a reputation, pay more the better you are, and are capped each year. Part-time jobs cut into school time and add stress",
      "The Occupation screen shows your full-time job, part-time job, odd-job reputation and work history",
    ],
  },
  {
    version: "2.0.0",
    title: "New Look, New Character",
    highlights: [
      "Menus work like BitLife now: tap a row and it opens its own screen, with a back button (and your browser's back button works too)",
      "Tap your face for a Profile screen, and tap any of the four stats for its history chart and what changed it this year",
      "Start a life in five steps: who you are, where you're born, meet your family, design your look (and preview yourself at any age), then begin",
      "You're born with a personality, two quirks and hidden talents that show up as you grow - and a family with real money (or the lack of it) that shapes your parents' jobs and your pocket money",
      "A brand-new avatar: 12 hairstyles, eye colours, beards, glasses, freckles, builds - and it ages with you: greying, balding, wrinkles, tired when you're unwell",
      "Stats finally matter: stress and fitness work behind the scenes, happiness no longer sits at 100 forever, and burnout can hit if you never slow down",
      "A real health system: illnesses, injuries and hospital bills, chronic and mental conditions, serious diagnoses you must decide how to handle, treatment, and insurance that depends on where you live",
      "Babies now announce their gender at birth, with name suggestions",
    ],
  },
  {
    version: "1.12.0",
    title: "Raising a Family",
    highlights: [
      "Parenting depends on how old your kid is: play and stories for the little ones, homework help and discipline as they grow - with real choices, never anything physical",
      "Your kids grow up: at 18 they head to college, find work or take time to figure things out, then meet someone, marry and maybe make you a grandparent",
      "Grandchildren are people too - spend time with them, give gifts and watch them grow",
      "Adult children can be nudged about a job, college, settling down or marriage - but it's their call. They can comply, refuse, and resent it. Refusals sting more where the culture expects it less",
      "Or skip the pressure and just pay for their college",
      "Couples who want kids now have a first-baby and a second-baby conversation as they get older",
    ],
  },
  {
    version: "1.11.0",
    title: "Exes and Consequences",
    highlights: [
      "Once you have an ex (at any age) you get a full set of options: text, call, chat, argue, send a gift, ask to get back together, or block them",
      "You can look them up online - and it can spiral: drive by, show up at their door, and it wears on your mind",
      "There's a hidden sanity stat. Stalking and spiralling wear it down, therapy rebuilds it, and the lower it is the more your unwanted contact looks like a threat",
      "Keep reaching out to someone who's moved on and they can file a restraining order. Comply, fight it with a public defender or a real lawyer, write an apology - or ignore it and risk arrest",
      "It goes the other way too: a volatile ex can start harassing you. Ignore it, block them, confront them, file your own order, or change your numbers",
      "Adults can also call an ex for a night - it can rekindle things, or blow up your current relationship",
      "New workplaces bring coworkers you can get to know, and adults can ask one out",
    ],
  },
  {
    version: "1.10.0",
    title: "Starting a Family",
    highlights: [
      "Adult couples (both 18+) can be intimate - with a real choice about protection when a baby is possible",
      "Fertility is a hidden stat for you and your partners and it changes with age and health, so timing matters",
      "If there's a pregnancy you find out right away and decide: keep the baby, plan an adoption, or not right now. If your partner is carrying, it's their decision too",
      "The baby arrives the following year - and you name them. A pregnancy can also end in a miscarriage",
      "Adoption is fleshed out: open, semi-open or closed. Stay in touch with letters and visits, or one day a grown child might come looking for you",
      "Same-gender couples and anyone who can't conceive naturally can use IVF, insemination, a donor or surrogacy",
      "Your partners have a hidden favor score too - it shapes how they respond to you",
    ],
  },
  {
    version: "1.9.0",
    title: "Life Goes On",
    highlights: [
      "The people in your life now age, get sick, change jobs, get married, have babies - and eventually pass away",
      "A new \"Around you\" section in your Life tab shows what's happening to everyone else, year by year",
      "When someone close dies you plan the funeral: cremation, a traditional burial, a lavish farewell, donating their body to science, or leaving it to the family - and you can give a eulogy",
      "Inheritance from parents and spouses, lingering grief, and an \"In memory\" list where you can leave flowers or remember them",
      "A relative can be diagnosed with something serious and you decide whether to be there, pay for treatment or keep your distance",
      "People ask you for money - give it, lend it, or say no - and friends slowly pay back what they owe",
      "Neglect people and your bond slips; friends you never see can drift away completely",
    ],
  },
  {
    version: "1.8.0",
    title: "People You Can Actually Talk To",
    highlights: [
      "Tap anyone in People to open their profile: bond, health, personality and everything you can do with them",
      "Talk to someone and you get a real conversation with choices - almost a hundred different scenes for parents, siblings, friends, partners, kids and more",
      "Go out, throw a party or have a sleepover - different places for kids, teens and adults",
      "Give money or ask for money with a slider - and what you borrow is remembered",
      "Ten gifts to choose from that change every year and for every person; watch how they react to learn what they like",
      "Dating opens at 13 through school: classmates can ask you out, first dates, holding hands, a first kiss, school dances - and breaking up gives you an ex at any age",
      "Every action has a yearly limit with diminishing returns, so you can't just spam one button",
    ],
  },
  {
    version: "1.7.1",
    title: "Real People",
    highlights: [
      "Everyone in your life now has an age, a job and a face that matches who they are",
      "Fixed a parent's passing naming the wrong parent - and it can now only happen to a parent who's actually old enough",
      "Popups can now hold lots of choices - they scroll, and can show who they're about",
      "Exes no longer drift back into a relationship after a single friendly text",
      "Groundwork for a big relationships update: talking, gifts, money, funerals and more",
    ],
  },
  {
    version: "1.7.0",
    title: "Alive",
    highlights: [
      "Some years now just pass quietly - popups are still the norm, but not every single year",
      "Events no longer repeat over and over - each one takes a break for years after it shows up",
      "Five themes to pick from: Midnight, Ocean, Sunset, Forest and Daylight (tap the palette button)",
      "Smoother, livelier motion - cards slide in, money counts up, stat changes float up, tabs bounce",
      "Your character's face reacts to how you're doing, and milestone birthdays get confetti",
    ],
  },
  {
    version: "1.6.0",
    title: "A Real Look",
    highlights: [
      "Your Life tab is now your full story - every year written down, with icons, instead of three lines and empty space",
      "Health, happiness, smarts and looks are always visible under your name",
      "Five tabs instead of seven: Life, Activities, People, Work, Money - with Crime and School folded into the right places",
      "People now have faces, grouped into Partner, Family, Friends and Exes, with relationship bars",
      "Redesigned Career, Money, Crime and Start screens, plus a bigger Age Up button that shows your next age",
      "Fixed partners being named \"Your partner\"",
    ],
  },
  {
    version: "1.5.1",
    title: "A Real Name Bank",
    highlights: [
      "Around 100 first names per gender and 110+ last names for every region - about 4x what was there",
      "Way more variety in family, friends, classmates, and dates - far fewer repeat names in a single life",
    ],
  },
  {
    version: "1.5.0",
    title: "Where You're From",
    highlights: [
      "A real country of origin - US, UK, Nigeria, Japan, or Brazil - with its own names, starting wealth, taxes, job market, and legal ages",
      "Surrender - a real, confirmed way to end a life on your own terms",
      "A real character avatar for the first time, built from your region and look",
      "Siblings and friends who show up on their own now always get a real name",
      "A visual pass - real elevation on cards, consolidated popups, color-coded tabs",
    ],
  },
  {
    version: "1.4.1",
    title: "What Just Happened",
    highlights: [
      "Every real action now shows a result popup - no more guessing what changed or digging through the yearly recap",
      "Hookups are a real choice now - use protection or don't, right before it happens",
      "Skip protection and there's a real chance of pregnancy - a real reveal popup, and a real choice to keep it or not",
      "Having a baby is a real moment now - born at the start of your next year, and you name them yourself",
    ],
  },
  {
    version: "1.4.0",
    title: "School, For Real",
    highlights: [
      "A new School tab - 4 real stages (elementary through college), 52 events, real classmates and faculty",
      "GPA, cliques, clubs, and a real roommate/rush/Greek-house college experience with multiple degrees",
      "Faculty actions - suck up, insult, report a classmate, and (in college) seduce a professor or dean",
      "Fighting is real now - attack anyone, win or lose, with rare real consequences",
      "Juvenile justice - an arrest under 18 means juvie and a real ankle monitor, not adult prison",
    ],
  },
  {
    version: "1.3.0",
    title: "Activities",
    highlights: [
      "A new Activities tab - 13 real venues from the library to the casino, each with its own effects",
      "Lessons build real skills (music, singing, art, martial arts, acting) for future fame careers",
      "Dating apps now show a real pool of matches to choose between, plus blind dates and hookups",
      "Birth control, IVF, insemination, donors, and sterilization - real reproductive choices",
      "Vacations, three tiers, that boost your family's relationships too if you bring them along",
    ],
  },
  {
    version: "1.2.0",
    title: "Court & Lawyers",
    highlights: [
      "Getting caught is now a real trial - plead guilty for a lighter, certain deal, or fight it in court",
      "Pick your defense: a free Public Defender, or pay for a Hired or Top Lawyer to shift the odds your way",
      "A crackdown can sweep the region - worse odds committing crimes and worse odds beating the charges",
      "Stay clean for 7 years and you can petition to expunge your record for good",
    ],
  },
  {
    version: "1.1.0",
    title: "Crime & Punishment (v1)",
    highlights: [
      "A new Crime tab - eight crimes across three tiers, real success odds shaped by your smarts",
      "Get caught and it's a real choice: pay bail and settle it, or can't pay and do real time",
      "Prison is its own life stage - no job, no random events, a sentence countdown, and a shot at parole",
      "A criminal record follows you - trust-based jobs (teacher, doctor, lawyer, and more) won't hire you anymore",
      "Getting arrested dings your credit score, same as any other real-world financial consequence",
    ],
  },
  {
    version: "1.0.0",
    title: "The money update",
    highlights: [
      "Real debt: personal loans and a revolving credit card, with a credit score that reacts to how you handle them",
      "A simulated stock market - six companies, prices that move with the economy, buy/sell with real gain/loss tracking",
      "Real progressive income tax, withheld automatically - your paycheck finally shows gross vs. take-home",
      "A 401(k)-style retirement account: pre-tax contributions, an employer match, and growth tied to the market",
      "Collapsible relationship rows - tap to expand instead of every action being on screen at once",
    ],
  },
];
